# Generated by Django 4.1.3 on 2023-05-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                default="anonymous.svg",
                null="anonymous.svg",
                upload_to="profile_images/",
            ),
        ),
    ]
