# Generated by Django 4.1.3 on 2023-05-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default_images/anonymous.svg",
                upload_to="profile_images/",
            ),
        ),
    ]
