# Generated by Django 4.1.3 on 2023-05-31 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("map", "0015_alter_eventinner_id"),
        ("users", "0008_userfollowing_userfavoriteeventinner_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFavoriteEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event_api",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="map.eventapi",
                    ),
                ),
                (
                    "event_inner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="map.eventinner",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserFavoriteProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.profile"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="userfavoriteeventinner",
            name="event",
        ),
        migrations.RemoveField(
            model_name="userfavoriteeventinner",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userfollowing",
            name="organizer",
        ),
        migrations.RemoveField(
            model_name="userfollowing",
            name="user",
        ),
        migrations.DeleteModel(
            name="UserFavoriteEventAPI",
        ),
        migrations.DeleteModel(
            name="UserFavoriteEventInner",
        ),
        migrations.DeleteModel(
            name="UserFollowing",
        ),
    ]
