# Generated by Django 4.1.3 on 2023-06-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_userfavoriteevent_userfavoriteprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="background_image",
            field=models.ImageField(
                blank=True, default="", upload_to="profile_images/"
            ),
        ),
    ]
