# Generated by Django 4.1.3 on 2023-06-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_profile_background_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="bio",
        ),
        migrations.AddField(
            model_name="profile",
            name="status",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
