# Generated by Django 4.1.3 on 2023-05-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(default=None, upload_to="events/"),
            preserve_default=False,
        ),
    ]
