# Generated by Django 4.1.3 on 2023-05-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0003_alter_event_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
