# Generated by Django 4.1.3 on 2023-05-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0004_alter_event_date_alter_event_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True, max_length=200, null=True, upload_to="event_images/"
            ),
        ),
    ]
