# Generated by Django 4.1.3 on 2023-05-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0005_alter_event_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="event_images/"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
