# Generated by Django 4.1.3 on 2023-05-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0007_alter_event_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
