# Generated by Django 4.1.3 on 2023-05-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0009_event_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventAPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("link", models.URLField(blank=True, max_length=500, null=True)),
                ("image", models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameModel(
            old_name="Event",
            new_name="EventInner",
        ),
    ]
