# Generated by Django 4.1.3 on 2023-05-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0010_eventapi_rename_event_eventinner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventapi",
            name="description",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="eventinner",
            name="description",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
