# Generated by Django 4.1.3 on 2023-05-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0012_alter_eventapi_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventapi",
            name="full_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
