# Generated by Django 4.1.3 on 2023-05-30 17:07

from django.db import migrations, models
import map.models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0014_eventinner_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventinner",
            name="id",
            field=models.CharField(
                default=map.models.generate_short_uuid,
                editable=False,
                max_length=10,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
